import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meerkat meme generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 h-[100vh] p-4`}
      >
        <header className="flex flex-col items-center justify-center text-center">
          <h1 className="text-3xl font-bold text-gray-900 mb-3">
            Meerkat meme Generator
          </h1>
          <p className="text-gray-600 text-xl">
            Create your own version of the classic Meerkat meme!
          </p>
        </header>
        {children}
      </body>
    </html>
  );
}
